server:
  port: 9003

spring:
  application:
    name: lagou-contract
  cloud:
    nacos:
      discovery:
        server-addr: http://10.253.130.23:8848/
        namespace: 73b9840a-ead1-449e-84f5-cc85c9106b8e