spring:
  application:
    name: lagou-cloud-eureka-server

server:
  port: 8761
eureka:
  instance:
    hostname: LagouCloudEurekaServerA
  client:
    register-with-eureka: true
    fetch-registry: true
   # service-url:
   #   defaultZone: http://LagouCloudEurekaServerB:8762/eureka
    service-url:
      defaultZone: http://localhost:8762/eureka/