spring:
  application:
    name: lagou-cloud-eureka-server

server:
  port: 8762
eureka:
  instance:
    hostname: LagouCloudEurekaServerB
  client:
    register-with-eureka: true
    fetch-registry: true
    #service-url:
    #  defaultZone: http://LagouCloudEurekaServerA:8761/eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/  #这里必须要写域名不能写别的